const INCREMENT_STEP = 'INCREMENT_STEP'
const INCREMENT = 'INCREMENT'
const DECREMENT = 'DECREMENT'
const DECREMENT_STEP = 'DECREMENT_STEP'

export default {INCREMENT_STEP, INCREMENT, DECREMENT, DECREMENT_STEP}